### ISSUE TITLE
现在使用您的代码携带cookie 还是返回202

### ISSUE THREAD

**Issue by AAAASJAAAA** [nciefeiniu/wenshu#1]
有解决的方法吗

**Comment by nciefeiniu** [comment]
@AAAASJAAAA 全部都是202？

**Comment by nciefeiniu** [comment]
@AAAASJAAAA 正常情况是有一些202的，只需要重试即可

**Comment by LewisLiu-AI** [comment]
一个cookies可以一直用吗，我用了好像不行，如果每次请求都要先请求一下splash，速度又会很慢

**Comment by nciefeiniu** [comment]
@WalkOnMars cookie只能使用一次。

大家都是程序员，程序员何必为难程序员，爬文书网速度慢点，太快了，文书网又更新反爬措施了。

**Comment by tzyGeneral** [comment]
现在好像又更新了，望大佬解答
