### ISSUE TITLE
大佬 url 拼接 HifJzoc9 这个参数如何生产

### ISSUE THREAD

**Issue by python-liuqingqing** [nciefeiniu/wenshu#4]

**Comment by nciefeiniu** [comment]
???什么，举个栗子

**Comment by python-liuqingqing** [comment]
![image](https://user-images.githubusercontent.com/35549309/70103539-5e2a3d80-1676-11ea-98ad-52ab637816b6.png)

**Comment by python-liuqingqing** [comment]
列表页，详情页url 拼接的一个参数，感谢 大佬

**Comment by nciefeiniu** [comment]
@python-liuqingqing 在我的印象里，这个后面的参数是无用的。

我刚刚测试了下，列表页面?后面的参数的确无效

**Comment by nciefeiniu** [comment]
这是个post请求，按照常理，传递的参数不会拼接在URL上的

**Comment by python-liuqingqing** [comment]
好的 非常感谢 大佬 😘

**Comment by tzyGeneral** [comment]
> 好的非常感谢大佬 😘

请问你是如何更换筛选条件来轮询的呢，望解答，感谢

**Comment by nciefeiniu** [comment]
@tzyGeneral 网站的有个js文件，里面有 案由 对应的 代码

post请求时携带上就能查询了

**Comment by tzyGeneral** [comment]
> @tzyGeneral 网站的有个js文件，里面有 案由 对应的 代码
> 
> post请求时携带上就能查询了

感谢大佬
