### ISSUE TITLE
请问有全部代码的demo，url后的HifJzoc9参数如何获取？

### ISSUE THREAD

**Issue by longwQaQ** [nciefeiniu/wenshu#8]
大佬，能否发一份你能跑的代码给我试试？

**Comment by nciefeiniu** [comment]
url后的参数不需要的。

这里只提供思路😢

**Comment by longwQaQ** [comment]
现在需要这个参数了，不加不行，你那边不加还能能用吗？

**Comment by nciefeiniu** [comment]
@lovemianhuatang 能用的，这post请求，后面的参数按照常理来说，是没用的。

我现在这边这个方法还能获取到数据的

**Comment by longwQaQ** [comment]
https://github.com/nciefeiniu/wenshu&nbsp; &nbsp;请问如何刷新ck?&nbsp; 使用是PyQtWebEngine&nbsp; &nbsp; 比如ck过期了&nbsp; &nbsp;要去获取新的ck&nbsp; &nbsp; &nbsp; &nbsp; 我用for&nbsp; 调用get_cookie（url） 只会执行一次就结束了
